export interface Match {
    id : number;
    city : string;
    matchDate : Date;
    manOftheMatch : string;
    venue : string;
    neutralVenue : any;
    firstTeam : string;
    secondTeam : string;
    tossWinner : string;
    tossDecision : string;
    winner : string;
    result : string;
    resultMargin : number;
    eliminator : any;
    method : string;
    umpireOne : string;
    umpireTwo : string;
    match : Match;
    inning : number;
    over : number;
    ball: number;
    batsman : string;
    nonStriker : string;
    bowler : string;
    batsmanRuns : number;
    extraRuns : number;
    totalRuns : number;
    nonBoundary : any;
    wicket : any;
    dismissalKind : string;
    playerDismissed : string;
    fielder : string;
    extrasType : string;
    battingTeam : string;
    bowlingTeam : string;
}
